export const baseConfig = {
  GRADES_LABEL: "Qualificações",
  HISTORIC_GRADES: "Classificações Históricas",
  GRADES_SCALES: "Escala de notas",
  DROPOUT_PREDICTION: "Previsão de desistência",
  DROPOUT_PREDICTION_DESCRIPTION:
    "O sistema estima uma probabilidade de abandono de",
  DROPOUT_PREDICTION_ACCURACY: "modelo de sucesso:",
  SEMESTRAL_GRADE_COLOR: "rgb(70,130,180)",
  CUMULATED_GRADE_COLOR: "rgb(173,66,244)",
  PROGRAM_GRADE_COLOR: "rgb(102,102,102)",
  STATE_PASSED_LABEL_MINI: "AP",
  STATE_FAILED_LABEL_MINI: "RE",
  STATE_CANCELED_LABEL_MINI: "AN",
  STATE_PENDING_LABEL_MINI: "PEN",
  STATE_CURRENT_LABEL_MINI: "CUR",
  SEARCH_BUTTON_LABEL: "Buscar",
  LOGOUT_BUTTON_LABEL: "Sair",
  SEMESTRAL_GRADE_LABEL: "PSP",
  CUMULATED_GRADE_LABEL: "PGA",
  PROGRAM_GRADE_LABEL: "PGA de carrera",
  FLOW_CIRCLE_COLOR: "rgb(245,101,101)",
  FLOW_CIRCLE_LABEL: "Fluj",
  REQ_CIRCLE_LABEL: "Req",
  REQ_CIRCLE_COLOR: "rgb(66,153,225)",
  ACTIVE_COURSE_BOX_COLOR: "gray.500",
  FLOW_COURSE_BOX_COLOR: "red.400",
  REQUISITE_COURSE_BOX_COLOR: "blue.400",
  EXPLICIT_SEMESTER_COURSE_BOX_COLOR: "yellow.400",
  INACTIVE_COURSE_BOX_COLOR: "gray.400",
  MIN_PASS_SCALE_COLOR: "#b0ffa1",
  MAX_PASS_SCALE_COLOR: "#5bff3b",
  MIN_FAIL_SCALE_COLOR: "#ff4040",
  MAX_FAIL_SCALE_COLOR: "#ff8282",
  STATE_COURSE_CURRENT_COLOR: "blue.500",
  STATE_COURSE_CANCELED_COLOR: "white",
  STATE_COURSE_PENDING_COLOR: "blue.300",
  STATE_COURSE_CIRCLE_STROKE: "white",
  COURSE_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  COURSE_BOX_TEXT_COLOR: "black",
  DROPOUT_BACKGROUND_COLOR: "rgb(252,249,165)",
  DROPOUT_TEXT_COLOR: "black",
  HISTOGRAM_BAR_ACTIVE: "rgb(122,122,122)",
  HISTOGRAM_BAR_INACTIVE: "rgb(191,191,191)",
  SEARCH_BAR_BACKGROUND_COLOR: "rgb(52,58,64)",
  TAKEN_SEMESTER_BOX_ACTIVE: "yellow.400",
  TAKEN_SEMESTER_BOX_INACTIVE: "grey",
  TAKEN_SEMESTER_BOX_BACKGROUND_COLOR: "rgb(245,245,245)",
  TAKEN_SEMESTER_BOX_TEXT_COLOR: "black",
  SEMESTER_HEADER_TEXT_COLOR: "rgb(70,130,180)",
  TIMELINE_TOOLTIP_TEXT_COLOR: "rgb(255,255,255)",
  TIMELINE_EXPLICIT_CIRCLE_COLOR: "rgb(236,201,75)",
  TIMELINE_AXIS_COLOR: "black",
  TIMELINE_AXIS_TEXT_COLOR: "black",
  TIMELINE_PASS_LINE_COLOR: "black",
  PASS_GRADE: 4,
  MIN_GRADE: 1,
  MAX_GRADE: 7,
  NO_CURRICULUMS_LABEL: "Sem planos",
  PROGRAM_NOT_SPECIFIED_PLACEHOLDER: "Programa não especificado",
  CURRICULUM_LABEL: "Planejamento",
  STUDENT_LABEL: "Estudante",
  PLACEHOLDER_SEARCH_STUDENT: "ID do estudante",
  STUDENT_LIST_TITLE: "Lista de estudantes",
  ENTRY_YEAR_LABEL: "Ingresso",
  PROGRESS_LABEL: "Progresso",
  RISK_LABEL: "Risco",
  RISK_HIGH_THRESHOLD: 80,
  RISK_HIGH_COLOR: "rgb(255,0,0)",
  RISK_MEDIUM_THRESHOLD: 50,
  RISK_MEDIUM_COLOR: "rgb(252,186,3)",
  RISK_LOW_COLOR: "rgb(128,255,0)",
  LOGIN_WRONG_INFO_MESSAGE:
    "Informações inseridas incorretamente. Verifique se os dados ou se sua conta pode estar bloqueada por segurança.",
  LOGIN_LOCKED_USER_MESSAGE:
    "Usuário bloqueado. Verifique o e-mail para recuperar sua conta.",
  LOGIN_PUT_VALID_EMAIL: "Digite um email válido",
  LOGIN_PUT_VALID_PASSWORD_LENGTH: "Digite uma senha de tamanho válida",
  LOGIN_EMAIL_LABEL: "Email",
  LOGIN_EMAIL_PLACEHOLDER: "email@ufrpe.br",
  LOGIN_PASSWORD_LABEL: "Senha",
  LOGIN_PASSWORD_PLACEHOLDER: "senha",
  LOGIN_REMEMBER_SESSION: "Fique conectado",
  LOGIN_BUTTON: "Entrar",
  LOGIN_ERROR_TITLE: "Erro!",
  UNLOCK_LENGTH_VALIDATION:
    "O tamanho da senha deve ter no mínimo 8 caracteres e no máximo 100 caracteres.",
  UNLOCK_SPECIAL_SYMBOL_VALIDATION: `A senha deve conter pelo menos um caractere especial (~¡!$&+,:;=¿?@#|'<>.^*(){}"% -_).`,
  UNLOCK_LOWERCASE_VALIDATION:
    "A senha deve conter pelo menos uma letra minúscula.",
  UNLOCK_UPPERCASE_VALIDATION:
    "A senha deve conter pelo menos uma letra maiúscula.",
  UNLOCK_NUMBER_VALIDATION: "A senha deve conter pelo menos um número.",
  UNLOCK_REPEAT_VALIDATION: "Você deve repetir sua senha corretamente.",
  UNLOCK_NEW_PASSWORD_LABEL: "Nova senha",
  UNLOCK_NEW_PASSWORD_PLACEHOLDER: "Senha",
  UNLOCK_NEW_PASSWORD_REPEAT_LABEL: "Repita sua senha",
  UNLOCK_ACTIVE_ACCOUNT_LABEL: "Ativar conta",
  UNLOCK_ERROR_TITLE: "Erro!",
  UNLOCK_WRONG_INFO_MESSAGE:
    "O usuário digitado não está bloqueado ou o código digitado está errado.",
  UNLOCK_USER_OLD_PASSWORD_MESSAGE:
    "Você não pode inserir uma senha usada anteriormente.",
  ERROR_STUDENT_NOT_FOUND_MESSAGE:
    "Não foi possível encontrar o aluno especificado no programa especificado.",
  ERROR_PROGRAM_UNAUTHORIZED_MESSAGE:
    "Você não está autorizado a assistir ao programa especificado",
  ERROR_PROGRAM_NOT_FOUND: "Não foi possível encontrar o programa especificado.",
  CHECK_STUDENT_FROM_LIST_LABEL: "Ver aluno",
  STATE_COLOR_PASS_FALLBACK: "rgb(102,180,62)",
  STATE_COLOR_FAIL_FALLBACK: "rgb(214,96,77)",
  CREDITS_LABEL: "Créditos",
  PARALLEL_GROUP_LABEL: "GP",
  PARALLEL_GROUP_BACKGROUND_COLOR: "#ddd",
  PARALLEL_GROUP_LABEL_COLOR: "black",
  COURSE_BOX_BORDER_WIDTH_ACTIVE: "2px",
  COURSE_BOX_BORDER_WIDTH_INACTIVE: "1px",
  CANCELED_HISTORIC_TOOLTIP_LABEL: "Anulada",
  NO_HISTORIC_DATA: "No hay datos a mostrar",
};
